parameters:
  ite_js.notifications.toastr_channel.class: ITE\Js\Notification\ToastrChannel

services:
  ite_js.notifications.channel.toastr:
    class: %ite_js.notifications.toastr_channel.class%
    arguments: [%ite_js.notifications.toastr_channel.version%]
    tags:
      - { name: ite_js.notification.channel }

  ite_notificator.toastr: "@ite_js.notifications.channel.toastr"