parameters:
  ite_js.notifications.toastr_extension.class: ITE\Js\Notification\ToastrExtension

services:
  ite_js.notifications.toastr_extension:
    class: %ite_js.notifications.toastr_extension.class%
    arguments: [%ite_js.notifications.toastr.version%]
    tags:
      - { name: ite_js.sf.extension, alias: 'notifications_toastr' }